var ezcheck,
    ezmojis,
    ezmsg = '...';

ezmojis = {
    // People
    bowtie: { code: ':bowtie:', emoji: ezmsg },
    smile: { code: ':smile:', emoji: '😄' },
    laughing: { code: ':laughing:', emoji: '😆' },
    blush: { code: ':blush:', emoji: '😊' },
    smiley: { code: ':smiley:', emoji: '😃' },
    relaxed: { code: ':relaxed:', emoji: ezmsg },
    smirk: { code: ':smirk:', emoji: '😏' },
    heart_eyes: { code: ':heart_eyes:', emoji: '😍' },
    kissing_heart: { code: ':kissing_heart:', emoji: '😘' },
    kissing_eyes_closed: { code: ':kissing_eyes_closed:', emoji: '😚' },
    flushed: { code: ':flushed:', emoji: '😳' },
    relieved: { code: ':relieved:', emoji: '😌' },
    satisfied: { code: ':satisfied:', emoji: '😆' },
    grin: { code: ':grin:', emoji: '😁' },
    wink: { code: ':wink:', emoji: '😉' },
    stuck_out_tongue_winking_eye: { code: ':stuck_out_tongue_winking_eye:', emoji: '😜' },
    stuck_out_tongue_closed_eye: { code: ':stuck_out_tongue_closed_eye:', emoji: '😝' },
    grinning: { code: ':grinning:', emoji: '😀' },
    kissing: { code: ':kissing:', emoji: '😗' },
    kissing_smiling_eyes: { code: ':kissing_smiling_eyes:', emoji: '😙' },
    stuck_out_tongue: { code: ':stuck_out_tongue:', emoji: '😛' },
    sleeping: { code: ':sleeping:', emoji: '😴' },
    worried: { code: ':worried:', emoji: '😟' },
    frowning: { code: ':frowning:', emoji: '😦' },
    anguished: { code: ':anguished:', emoji: '😧' },
    open_mouth: { code: ':open_mouth:', emoji: '😮' },
    grimacing: { code: ':grimacing:', emoji: '😬' },
    confused: { code: ':confused:', emoji: '😕' },
    hushed: { code: ':hushed:', emoji: '😯' },
    expressionless: { code: ':expressionless:', emoji: '😑' },
    unamused: { code: ':unamused:', emoji: '😒' },
    sweat_smile: { code: ':sweat_smile:', emoji: '😅' },
    sweat: { code: ':sweat:', emoji: '😓' },
    disappionted_relieved: { code: ':disappionted_relieved:', emoji: '😥' },
    weary: { code: ':weary:', emoji: '😩' },
    pensive: { code: ':pensive:', emoji: '😔' },
    disappionted: { code: ':disappionted:', emoji: '😞' },
    confounded: { code: ':confounded:', emoji: '😖' },
    fearful: { code: ':fearful:', emoji: '😨' },
    cold_sweat: { code: ':cold_sweat:', emoji: '😰' },
    persevere: { code: ':persevere:', emoji: '😣' },
    cry: { code: ':cry:', emoji: '😢' },
    sob: { code: ':sob:', emoji: '😭' },
    joy: { code: ':joy:', emoji: '😂' },
    astonished: { code: ':astonished:', emoji: '😲' },
    scream: { code: ':scream:', emoji: '😱' },
    neckbeard: { code: ':neckbeard:', emoji: ezmsg },
    tired_face: { code: ':tired_face:', emoji: '😫' },
    angry: { code: ':angry:', emoji: '😠' },
    rage: { code: ':rage:', emoji: '😡' },
    triumph: { code: ':triumph:', emoji: '😤' },
    sleepy: { code: ':sleepy:', emoji: '😪' },
    yum: { code: ':yum:', emoji: '😋' },
    mask: { code: ':mask:', emoji: '😷' },
    sunglasses: { code: ':sunglasses:', emoji: '😎' },
    dizzy_face: { code: ':dizzy_face:', emoji: '😵' },
    imp: { code: ':imp:', emoji: '👿' },
    smiling_imp: { code: ':smiling_imp:', emoji: '😈' },
    neutral_face: { code: ':neutral_face:', emoji: '😐' },
    no_mouth: { code: ':no_mouth:', emoji: '😶' },
    innocent: { code: ':innocent:', emoji: '😇' },
    alien: { code: ':alien:', emoji: '👽' },
    yellow_heart: { code: ':yellow_heart:', emoji: '💛' },
    blue_heart: { code: ':blue_heart:', emoji: '💙' },
    purple_heart: { code: ':purple_heart:', emoji: '💜' },
    heart: { code: ':heart:', emoji: '❤️' },
    green_heart: { code: ':green_heart:', emoji: '💚' },
    broken_heart: { code: ':broken_heart:', emoji: '💔' },
    heartbeat: { code: ':heartbeat:', emoji: '💓' },
    heartpulse: { code: ':heartpulse:', emoji: '💗' },
    two_hearts: { code: ':two_hearts:', emoji: '💕' },
    revolving_hearts: { code: ':revolving_hearts:', emoji: '💞' },
    cupid: { code: ':cupid:', emoji: '💘' },
    sparkling_heart: { code: ':sparkling_heart:', emoji: '💖' },
    sparkles: { code: ':sparkles:', emoji: '✨' },
    star: { code: ':star:', emoji: '⭐️' },
    star2: { code: ':star2:', emoji: '🌟' },
    dizzy: { code: ':dizzy:', emoji: '💫' },
    boom: { code: ':boom:', emoji: '💥' },
    collision: { code: ':collision:', emoji: '💥' },
    anger: { code: ':anger:', emoji: '💢' },
    exclamation: { code: ':exclamation:', emoji: '❗️' },
    question: { code: ':question:', emoji: '❓' },
    grey_exclamation: { code: ':grey_exclamation:', emoji: '❕' },
    grey_question: { code: ':grey_question:', emoji: '❔' },
    zzz: { code: ':zzz:', emoji: '💤' },
    dash: { code: ':dash:', emoji: '💨' },
    sweat_drops: { code: ':sweat_drops:', emoji: '💦' },
    notes: { code: ':notes:', emoji: '🎶' },
    musical_note: { code: ':musical_note:', emoji: '🎵' },
    fire: { code: ':fire:', emoji: '🔥' },
    hankey: { code: ':hankey:', emoji: '💩' },
    poop: { code: ':poop:', emoji: '💩' },
    shit: { code: ':shit:', emoji: '💩' },
    plusone: { code: ':+1:', emoji: '👍' },
    thumbsup: { code: ':thumbsup:', emoji: '👍' },
    minusone: { code: ':-1:', emoji: '👎' },
    thumbsdown: { code: ':thumbsdown:', emoji: '👎' },
    ok_hand: { code: ':ok_hand:', emoji: '👌' },
    punch: { code: ':punch:', emoji: '👊' },
    facepunch: { code: ':facepunch:', emoji: '👊' },
    fist: { code: ':fist:', emoji: '✊' },
    v: { code: ':v:', emoji: '✌️' },
    wave: { code: ':wave:', emoji: '👋' },
    hand: { code: ':hand:', emoji: '✋' },
    raised_hand: { code: ':raised_hand:', emoji: '✋' },
    open_hands: { code: ':open_hands:', emoji: '👐' },
    point_up: { code: ':point_up:', emoji: '☝️' },
    point_down: { code: ':point_down:', emoji: '👇' },
    point_left: { code: ':point_left:', emoji: '👈' },
    point_right: { code: ':point_right:', emoji: '👉' },
    raised_hands: { code: ':raised_hands:', emoji: '🙌' },
    pray: { code: ':pray:', emoji: '🙏' },
    point_up_2: { code: ':point_up_2:', emoji: '👆' },
    clap: { code: ':clap:', emoji: '👏' },
    muscle: { code: ':muscle:', emoji: '💪' },
    metal: { code: ':metal:', emoji: '🤘' },
    fu: { code: ':fu:', emoji: '🖕' },
    walking: { code: ':walking:', emoji: '🚶' },
    runner: { code: ':runner:', emoji: '🏃' },
    running: { code: ':running:', emoji: '🏃' },
    couple: { code: ':couple:', emoji: '👫' },
    family: { code: ':family:', emoji: '👪' },
    two_men_holding_hands: { code: ':two_men_holding_hands:', emoji: '👬' },
    two_women_holding_hands: { code: ':two_women_holding_hands:', emoji: '👭' },
    dancer: { code: ':dancer:', emoji: '💃' },
    dancers: { code: ':dancers:', emoji: '👯' },
    ok_woman: { code: ':ok_woman:', emoji: '🙆' },
    no_good: { code: ':no_good:', emoji: '🙅' },
    information_desk_person: { code: ':information_desk_person:', emoji: '💁' },
    raising_hand: { code: ':raising_hand:', emoji: '🙋' },
    bride_with_veil: { code: ':bride_with_veil:', emoji: '👰' },
    person_with_pouting_face: { code: ':person_with_pouting_face:', emoji: '🙎' },
    person_frowning: { code: ':person_frowning:', emoji: '🙍' },
    bow: { code: ':bow:', emoji: '🙇' },
    couplekiss: { code: ':couplekiss:', emoji: ezmsg },
    couple_with_heart: { code: ':couple_with_heart:', emoji: '💑' },
    massage: { code: ':massage:', emoji: '💆' },
    haircut: { code: ':haircut:', emoji: '💇' },
    nail_care: { code: ':nail_care:', emoji: '💅' },
    boy: { code: ':boy:', emoji: '👦' },
    girl: { code: ':girl:', emoji: '👧' },
    woman: { code: ':woman:', emoji: '👩' },
    man: { code: ':man:', emoji: '👨' },
    baby: { code: ':baby:', emoji: '👶' },
    older_woman: { code: ':older_woman:', emoji: '👵' },
    older_man: { code: ':older_man:', emoji: '👴' },
    person_with_blond_hair: { code: ':person_with_blond_hair:', emoji: '👱' },
    man_with_gua_pi_mao: { code: ':man_with_gua_pi_mao:', emoji: '👲' },
    man_with_turban: { code: ':man_with_turban:', emoji: '👳' },
    construction_worker: { code: ':construction_worker:', emoji: '👷' },
    cop: { code: ':cop:', emoji: '👮' },
    angel: { code: ':angel:', emoji: '👼' },
    princess: { code: ':princess:', emoji: '👸' },
    smiley_cat: { code: ':smiley_cat:', emoji: '😺' },
    smile_cat: { code: ':smile_cat:', emoji: '😸' },
    heart_eyes_cat: { code: ':heart_eyes_cat:', emoji: '😻' },
    kissing_cat: { code: ':kissing_cat:', emoji: '😽' },
    smirk_cat: { code: ':smirk_cat:', emoji: '😼' },
    scream_cat: { code: ':scream_cat:', emoji: '🙀' },
    crying_cat_face: { code: ':crying_cat_face:', emoji: '😿' },
    joy_cat: { code: ':joy_cat:', emoji: '😹' },
    pouting_cat: { code: ':pouting_cat:', emoji: '😾' },
    japanese_ogre: { code: ':japanese_ogre:', emoji: '👹' },
    japanese_goblin: { code: ':japanese_goblin:', emoji: '👺' },
    see_no_evil: { code: ':see_no_evil:', emoji: '🙈' },
    hear_no_evil: { code: ':hear_no_evil:', emoji: '🙉' },
    speak_no_evil: { code: ':speak_no_evil:', emoji: '🙊' },
    guardsman: { code: ':guardsman:', emoji: '💂' },
    skull: { code: ':skull:', emoji: '💀' },
    feet: { code: ':feet:', emoji: '🐾' },
    lips: { code: ':lips:', emoji: '👄' },
    kiss: { code: ':kiss:', emoji: '💋' },
    droplet: { code: ':droplet:', emoji: '💧' },
    ear: { code: ':ear:', emoji: '👂' },
    eyes: { code: ':eyes:', emoji: '👀' },
    nose: { code: ':nose:', emoji: '👃' },
    tongue: { code: ':tongue:', emoji: '👅' },
    love_letter: { code: ':love_letter:', emoji: '💌' },
    bust_in_silhouette: { code: ':bust_in_silhouette:', emoji: '👤' },
    busts_in_silhouette: { code: ':busts_in_silhouette:', emoji: '👥' },
    speech_balloon: { code: ':speech_balloon:', emoji: '💬' },
    thought_balloon: { code: ':thought_balloon:', emoji: '💭' },
    feelsgood: { code: ':feelsgood:', emoji: ezmsg },
    finnadie: { code: ':finnadie:', emoji: ezmsg },
    goberserk: { code: ':goberserk:', emoji: ezmsg },
    godmode: { code: ':godmode:', emoji: ezmsg },
    hurtrealbad: { code: ':hurtrealbad:', emoji: ezmsg },
    rage1: { code: ':rage1:', emoji: ezmsg },
    rage2: { code: ':rage2:', emoji: ezmsg },
    rage3: { code: ':rage3:', emoji: ezmsg },
    rage4: { code: ':rage4:', emoji: ezmsg },
    suspect: { code: ':suspect:', emoji: ezmsg },
    trollface: { code: ':trollface:', emoji: ezmsg }
};

ezcheck = function(node) {
    for (const emoji in ezmojis) {
        if(node.innerText.includes(ezmojis[emoji].code)) {
            var nstr = node.innerText.replace(ezmojis[emoji].code, ezmojis[emoji].emoji);
            return node.innerText = nstr;
        }
    };
};

function ezinit(node) {
    var nodes = node.childNodes;
    for (var i = 0; i <nodes.length; i++) {
        if(!nodes[i]) { continue }
        if(nodes[i].childNodes.length > 0) {
            ezinit(nodes[i]);
            if(nodes[i].tagName !== 'HTML' && nodes[i].tagName !== 'BODY') { ezcheck(nodes[i]) };
        };
    };
};

ezinit(document);
